### ISSUE TITLE
Branding Ufficiale - i 4 you

### ISSUE THREAD

**Issue by calca** [okja-team/okja#2]
Creazione Branding ufficiale :

- logo ( i 4 you)
- splah app
- banner / store

**Comment by Alfr3d** [comment]
Idea LOGO e Icona per app Android
![logo](https://user-images.githubusercontent.com/1813054/76688863-234e8300-6631-11ea-804a-11c95fe0f5c3.png)

**Comment by calca** [comment]
logo approvato.  (anche i colori)

Lavoriamo sul fonto della scitta e la palette colore per l'app da dare al team di @citerad

**Comment by Alfr3d** [comment]
Arrivano altre proposte FONT for logo App. Il font per la UI e la UX la scelgo di seguito.

**Comment by calca** [comment]
@Alfr3d  scaricati il repo, e creare nella root assest/ con tutto il materiale

**Comment by Alfr3d** [comment]
Font per il logo > https://fonts.google.com/specimen/Nothing+You+Could+Do
![logo](https://user-images.githubusercontent.com/1813054/76689330-16339300-6635-11ea-8f38-c01b44200624.png)

**Comment by Alfr3d** [comment]
Pensavo ad uno splash del genere.
![Splash](https://user-images.githubusercontent.com/1813054/76689781-ad024e80-6639-11ea-9756-26522fb39ce1.png)

**Comment by calca** [comment]
Si perfetta, essenziale e pulita.

**Comment by Alfr3d** [comment]
Logo no claim.
![logo_no_claim](https://user-images.githubusercontent.com/1813054/76696924-eade9180-6690-11ea-9131-803a39de2d4d.png)

**Comment by Alfr3d** [comment]
Claim no logo
![claim_no_logo_bw](https://user-images.githubusercontent.com/1813054/76697138-6b9e8d00-6693-11ea-9ac1-12d2b0b53b8c.png)
![claim_no_logo](https://user-images.githubusercontent.com/1813054/76697139-6c372380-6693-11ea-8bcb-2ccc79b36a45.png)

**Comment by calca** [comment]
bene!

**Comment by Alfr3d** [comment]
Fatto commit con gli assets in svg di cui sopra. Inoltre creata anche favicon.

**Comment by calca** [comment]
@Alfr3d  se puoi, anche una cartella assets/ nella root con gli elementi PNG da utilizzare fuori dall'app (app store, sito ecc.. ) grazie

**Comment by Alfr3d** [comment]
Logo da usare per lo splash. Importo anche il font così usiamo solo l'immagine vettoriale.
![logo_for_splash](https://user-images.githubusercontent.com/1813054/76703485-454c1200-66d2-11ea-83bc-238279525cdf.png)

**Comment by alfredarcifa** [comment]
@calca con un tool sono riuscito a creare splash e ico per android e ios
Non sono i migliori splash e ico ma intanto li ho uploadati committati e pushati

https://apetools.webprofusion.com/#/tools/imagegorilla

**Comment by calca** [comment]
bene, ci sta per l'mvp!

**Comment by alfredarcifa** [comment]
in root dir creata cartella assets

root
|_ devDocs
|_ docs
|_ mobile
|_ assets
