### ISSUE TITLE
Mappa con le persone vicine che possono aiutare

### ISSUE THREAD

**Issue by calca** [okja-team/okja#3]
Visualizza come prima tab la mappa della posizione in cui mi trovo e le persone vicine che mi possono aiutare

**Comment by ammiratafabiano** [comment]
google maps?

**Comment by calca** [comment]
si direi di si, plugin di cordova/ionic ufficiale

**Comment by calca** [comment]
chiediamo ad @Alfred l'icona

**Comment by alfred** [comment]
?

**Comment by calca** [comment]
icona per la persona 'aiutente' sulla mappa di google maps

**Comment by Alfr3d** [comment]
![maps_help_icon](https://user-images.githubusercontent.com/1813054/76696787-64758000-668f-11ea-9d58-5458e1c425f0.png)

**Comment by Alfr3d** [comment]
O questa che enfatizza dai colori il bisogno di aiuto

![maps_help_icon_2](https://user-images.githubusercontent.com/1813054/76696825-e5cd1280-668f-11ea-87c8-03ec70f1f8cf.png)

**Comment by calca** [comment]
ci sta. Ce ne serve una anche per chi dona aiuto :)

**Comment by Alfr3d** [comment]
Si, stavo cercando anche

**Comment by Alfr3d** [comment]
![help_you](https://user-images.githubusercontent.com/1813054/76701369-d619f200-66c0-11ea-83ed-a35b9d299a91.png)

**Comment by calca** [comment]
ok, ci siamo
