### ISSUE TITLE
GoogleMaps API Keys

### ISSUE THREAD

**Issue by citerad** [okja-team/okja#31]

**Comment by Alfr3d** [comment]
Si può anche pensare di usare altre librerie qualora dovessimo comprare licenza

**Comment by calca** [comment]
partiamo con Google maps. capiamo poi se passare ad openstreet

**Comment by calca** [comment]
per ora google mi ha dato 300$ per un anno, partiamo con l'MVP nel caso cambiamo provider di mappe (openstreetmaps)

**Comment by calca** [comment]
https://www.mapbox.com/pricing/
