### ISSUE TITLE
Visualizzazione lista tab2

### ISSUE THREAD

**Issue by ammiratafabiano** [okja-team/okja#32]
Lista di card degli aiutanti. Cliccando sulla card si andrà su una pagina dell'aiutante che sarà la stessa di quando si clicca sull'anteprima che spunta nella visualizzazione mappa. Filtri basic per ordinamento e tipologie di aiuto.

**Comment by ammiratafabiano** [comment]
@calca posso procedere con issue #32 e #33 ?

**Comment by calca** [comment]
Si, va bene. perfetto Usiamo le cards di ionic 5. @Alfr3d  ci serve un header umano quando @ammiratafabiano  ci posta l'anteprima

**Comment by alfredarcifa** [comment]
@ammiratafabiano fammi sapere

**Comment by ammiratafabiano** [comment]
@Alfr3d tra un po pusho nel branch feature/cards la versione attuale e ti lascio il testimone

**Comment by ammiratafabiano** [comment]
Fatto! Fammi sapere che ne pensi

**Comment by ammiratafabiano** [comment]
PS: ho salito anche il mock così non devi fartelo anche tu, ovviamente poi togliamolo quando si sale in develop

**Comment by alfredarcifa** [comment]
Mi dava errore in fase di compilazione, mancava la libreria:
"@ionic-native/call-number": "^5.22.0",

@ammiratafabiano mò do un occhio.

**Comment by ammiratafabiano** [comment]
Va bene va bene! Fammi sapere :)
