### ISSUE TITLE
Registrazione Aiutanti

### ISSUE THREAD

**Issue by calca** [okja-team/okja#4]
bottone registrazione aiutante 

- nome
- cognome
- indirizzo
- contatto
- aiuto offerto ( farmacia, spesa, compania)

**Comment by calca** [comment]
Utilizzo di provider esterni registrazione veloce (google/facebook..)

**Comment by calca** [comment]
Un esempio di card
https://www.theguardian.com/world/2020/mar/14/coronavirus-campaign-launched-offering-help-to-those-self-isolating?CMP=Share_iOSApp_Other

![image](https://user-images.githubusercontent.com/78342/76686211-1bcfaf80-661a-11ea-8cb3-2aee0b8d8b40.png)

**Comment by il-picchio** [comment]
![image](https://user-images.githubusercontent.com/59490290/76686971-11b0af80-6620-11ea-9314-96ec7616af7d.png)

Una cosa così?

**Comment by calca** [comment]
Si, dire perfetto così pe sprint 0

**Comment by calca** [comment]
@Alfr3d un'inconcina carina da mettere in alto ;)

**Comment by il-picchio** [comment]
tema chiaro

![image](https://user-images.githubusercontent.com/59490290/76690283-d5407c00-663e-11ea-8bea-43f2c128029f.png)


tema scuro

![image](https://user-images.githubusercontent.com/59490290/76690292-e38e9800-663e-11ea-839e-f0e40583d631.png)

**Comment by il-picchio** [comment]
per tornare indietro abbiamo già un'idea se mettere un header fixed on top o un pulsante sotto "registrati" tipo "torna indietro" ?

**Comment by calca** [comment]
mettiamo un 'non ora', e torna indietro

**Comment by calca** [comment]
tema chiarmo molto bello. per lo scuro non c'è lo swithc dell'immagine ?

**Comment by il-picchio** [comment]
lo switch lo aggiungo volentieri ma avrei bisogno di un'altra immagine @Alfr3d ;)

**Comment by calca** [comment]
è qui per noi :D

**Comment by calca** [comment]
per il resto direi che come primo giro è buono. @citerad  ?  
La parte importante di questa pagian è il picker della posizione. c'è già qualcosa che possiamo utilzizare ?

**Comment by il-picchio** [comment]
qualcosa del genere? https://www.gianlucaghettini.net/ricerca-localita-completamento-automatico-google-api/

**Comment by calca** [comment]
non esiste un picker ?

**Comment by calca** [comment]
https://www.joshmorony.com/location-select-page-with-google-maps-and-ionic/

forse per ora conviene stare su questo

**Comment by Alfr3d** [comment]
@il-picchio 
![BisognoAiuto_black](https://user-images.githubusercontent.com/1813054/76696642-11e79400-668e-11ea-86cf-63db00998c44.png)

**Comment by il-picchio** [comment]
Quando si imposta il profilo "in bisogno di aiuto" si deve anche specificare di cosa si ha bisogno o si decide volta per volta?

**Comment by calca** [comment]
il mio dubbio, che non tutte le persone vorranno mettere 'ho bisogno di aiuto'. Cmq si, anche si cosa ha bisogno, così una persona può aiutarla

**Comment by il-picchio** [comment]
Quindi una persona può sia essere bisognosa che aiutante?

**Comment by calca** [comment]
starei sul facile, stato esclusivo. o bisognosa o aiutante

**Comment by il-picchio** [comment]
ok allora se tiriamo dentro a parte il selettore di posizione (che crco di fare entro serata) la pagina è pronta

**Comment by il-picchio** [comment]
ok allora a parte il selettore di posizione (cerco entro sera) e qualche ritocco dovrebbe essere pronta, se tiriamo dentro riusciamo a fasarci meglio

**Comment by calca** [comment]
senti @citerad che lo stava integrando

**Comment by il-picchio** [comment]
@citerad forse è meglio integrarlo e lavorare tutti sulla stessa cosa ;) pensavo di doverlo fare io essendomi assegnato la parte di registrazione
