### ISSUE TITLE
implementazione plugin per login con google

### ISSUE THREAD

**Issue by falconeta** [okja-team/okja#44]

**Comment by calca** [comment]
che dite (@citerad) di utilizzare solo provider ? Google / Facebook e rimuovere la registrazione. lo vedete come un problema ?

**Comment by citerad** [comment]
@calca sono d'accordo, va creata un app per ogni provider...per ora lasciamo quella manuale per fare i test

**Comment by calca** [comment]
ok, poi li creo per i principali. iniziamo con Google e Facebook

**Comment by il-picchio** [comment]
Che ne pensate di una login così (ci sarebbero i loghi da sistemare in caso ;) )?


![image](https://user-images.githubusercontent.com/59490290/76706952-b3e99980-66eb-11ea-898f-a35156b51d51.png)

![image](https://user-images.githubusercontent.com/59490290/76706962-c663d300-66eb-11ea-905f-341fcd6d5ffd.png)

**Comment by calca** [comment]
direi di sì, mettiamo un Accedi ed il testo del volontario qui? @@alfred immaginetta ?

**Comment by il-picchio** [comment]
Il testo del volontario?

**Comment by calca** [comment]
sì, c'è la issue. per ora mettiamo un testo semplice
