### ISSUE TITLE
Sezione Profilo

### ISSUE THREAD

**Issue by citerad** [okja-team/okja#53]
Per la sezione del profilo bisognerà:

- inserire correttamente i binding tra il model del profilo e la pagina dedicata
- utilizzare l'enum RoleType con mappatura adeguata per visualizzare l'elenco dei possibili aiuti
- inserire uno swith/tab per passare dalla modalità helper alla modalità non helper dove:
** la modalità helper visualizzerà all'interno del profilo oltre ai dati utente e in cosa può aiutare (RoleType) un flag per indicare la sua disponibilità ad essere contattato e un bottone per selezionare la posizione ( #55 ) 
** la modalità non helper visualizzerà solo le informazioni di dati utente
Nel caso in cui l'utente cerca di salvare il profilo, la modifica non è consentita se non ha inserito i dati obbligatori (es posizione)

Ad ogni salvataggio del profilo in caso di utente helper, questo dovrà essere inserito come active_user, nel caso contrario dovà essere effettuata una rimozione del profilo da active_user

**Comment by alfredarcifa** [comment]
Ho rivisto la UI del PROFILE PAGE. 
Il flow prevede due step.

![Page_profile](https://user-images.githubusercontent.com/1813054/76940988-8115f000-68fb-11ea-85dc-fc97f6c0d2b2.png)

**Comment by calca** [comment]
punti di attenzione:

- contatti: non è solo telefono. per fase 1 phone e skype
- aiuti: anche una chatta/telefonata/videocall di supproto

@citerad  la location è obbligatoria ?

**Comment by alfredarcifa** [comment]
> punti di attenzione:
> 
> * contatti: non è solo telefono. per fase 1 phone e skype
> * aiuti: anche una chatta/telefonata/videocall di supproto
> 
> @citerad la location è obbligatoria ?

ma direi che con whatsapp ormai copri sia le chat che i video. Skype lo ometterei.

**Comment by calca** [comment]
magari qualcuno non vuole condividere il proprio cell ed allora è contatabile con skype o fb messanger

**Comment by alfredarcifa** [comment]
It is useful for me to have a gender selection.
For example, if I am an older woman, a helper woman has more confidence than a male person.

**Comment by citerad** [comment]
> punti di attenzione:
> 
> * contatti: non è solo telefono. per fase 1 phone e skype
> * aiuti: anche una chatta/telefonata/videocall di supproto
> 
> @citerad la location è obbligatoria ?

la location dovrebbe essere obbligatoria per gli helper, altrimenti non si riesce a definire la distanza.
al massimo si potrebbe pensare di inserire un flag per nasconderla dalla mappa ma lasciare comunque l'helper visibile nella lista (se disponibile)

**Comment by calca** [comment]
ok, flag privacy per la location in sprint 2 , #67
