### ISSUE TITLE
Tab Mappa

### ISSUE THREAD

**Issue by citerad** [okja-team/okja#54]
Ad ogni atterraggio sulla pagina la mappa dovrà essere refreshata.
Il centro della mappa dovrà essere riposizionato per consentire la visualizzazione di tutti i pin restituiti dal servizio.
Al tap su un pin dovrà aprirsi una card che mostra le informazioni dell'helper (con la possibilità di contattarlo).
La pagina dovrà contenere un bottone per consentire la modifica del profilo

**Comment by gianlu92** [comment]
Sviluppi iniziati sul branch Issue-54-tab-mappa
![image](https://user-images.githubusercontent.com/62199681/76890349-7e79b300-6887-11ea-8051-6753eefb7d91.png)

**Comment by gianlu92** [comment]
Per contattare si intende il poter chiamare direttamente da app o che apre un'altra schermata?

**Comment by calca** [comment]
altra app. l'utente inserirà Cell, skypid .. demandiamo alle app standard il contato tra le persone

**Comment by calca** [comment]
se possibile togliere anche l'header del tab,  fullscreen la mappa e solo i 3 switch

**Comment by gianlu92** [comment]
> altra app. l'utente inserirà Cell, skypid .. demandiamo alle app standard il contato tra le persone

Ok quindi immagino che in base a quale informazione di contatto l'utente abbia messo si apriranno varie app (dialer se ha valorizzato il numero di telefono, skype se ha valorizzato SkypeId ecc).
Corretto?

**Comment by citerad** [comment]
Verranno mostrate tutte le tipologie di contratto inserire dall'helper. In base alla tipologia tappata da chi richiede aiuto si aprirà l'app corrispondente.

**Comment by calca** [comment]
si, per la prima versione starei su numero di cell e skype per video chiamata, poi estendiamo
