### ISSUE TITLE
ActiveProfilePage UI

### ISSUE THREAD

**Issue by citerad** [okja-team/okja#71]
- Complete UI.
- Replace the card with ionic-action-sheet or modal.
- Insert profile picture at the top right

![Mobile - Page - Maps HELPER](https://user-images.githubusercontent.com/5503000/77247385-fe5d9f80-6c30-11ea-9738-b01fac9e560e.png)

**Comment by calca** [comment]
- TabBar v1 : done
- UserBadge v1 : done (static image)
