### ISSUE TITLE
ProfilePage - OnBoarding UI

### ISSUE THREAD

**Issue by citerad** [okja-team/okja#72]
Complete the profile UI

![Mobile - Page - Profile](https://user-images.githubusercontent.com/5503000/77247424-7b891480-6c31-11ea-8d5e-e721a06b1297.png)

**Comment by calca** [comment]
@Alfr3d ci sono gli asset di questi ?

**Comment by alfredarcifa** [comment]
[assets_profile.zip](https://github.com/okja-team/okja/files/4371099/assets_profile.zip)

**Comment by calca** [comment]
![localhost_8101_home_tabs_map(iPhone X) (2)](https://user-images.githubusercontent.com/78342/77705680-9c9a8e00-6fc0-11ea-859a-52ed4bf90da3.png)
![localhost_8101_home_tabs_map(iPhone X) (1)](https://user-images.githubusercontent.com/78342/77705683-9f957e80-6fc0-11ea-8dcb-fff230bbb2f3.png)
