### ISSUE TITLE
Pagina Privacy e Cancella utente

### ISSUE THREAD

**Issue by calca** [okja-team/okja#9]
Pagina con

- info sulla privacy
- delete account

**Comment by ammiratafabiano** [comment]
facciamo pagina a parte e poi la linkiamo da qualche parte oppure il terzo tab?

**Comment by citerad** [comment]
farei primo tab mappa, secondo settings terzo privacy  - delete @calca ?

**Comment by calca** [comment]
si va bene.

se facciamo la pagina dei settings, il bototne delete mettiamoli li (non ci avevo pensato).
Una modifica le sue opzione e un bel 'cancella il mio utente'

**Comment by ammiratafabiano** [comment]
controproposta: primo tab visualizzazione mappa mappa, secondo tab visualizzazione lista, terzo tab settings e ci mettiamo diversi bottoni come info privacy e delete account

**Comment by calca** [comment]
ok, @ammiratafabiano  mi piace. andiamo così per il primo giro

**Comment by vitacito** [comment]
nel settings ci mettiamo anche logout global app style :D

**Comment by calca** [comment]
@vitacito  giusto, anche il logout (usato pochissimo) @ammiratafabiano  aggiungilo ai bottoni del tab settings (come da proposta Ui di @il-picchio )

**Comment by ammiratafabiano** [comment]
yes! per sprint 0 che facciamo con scritte dentro le pagine? scritte direttamente? italiano?

**Comment by calca** [comment]
ho una amico che ci farebbe la versione inglese. la vedi difficile per lo sprint 0 ?

**Comment by ammiratafabiano** [comment]
ci provo, mi metto all'opera, quindi mi sto occupando di tab3 e translateConfig

**Comment by calca** [comment]
@ammiratafabiano @il-picchio  ha iniziato in un branch

**Comment by calca** [comment]
[avviso_VOLONTARI.stamped.pdf](https://github.com/okja-team/okja/files/4333252/avviso_VOLONTARI.stamped.pdf)

Questo il volontano del mio comune per la gestione della responsabilità, prendiamo spunto da li
